/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionPointCard: typeof import('./src/components/card/collection-point-card.vue')['default']
    DomusMap: typeof import('./src/components/map/domus-map.vue')['default']
    DomusMapGoogle: typeof import('./src/components/map/domus-map-google.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    SplashScreen: typeof import('./src/components/splash-screen/splash-screen.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  }
}
