/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CollectionPointCard: typeof import('./src/components/card/collection-point-card.vue')['default']
    CollectionPointCardDesktop: typeof import('./src/components/card/collection-point-card-desktop.vue')['default']
    CollectionPointDetails: typeof import('./src/components/card/collection-point-details.vue')['default']
    DomusMapGoogle: typeof import('./src/components/map/domus-map-google.vue')['default']
    DomusMapGoogleDesktop: typeof import('./src/components/map/domus-map-google-desktop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search-bar/search-bar.vue')['default']
    SearchBarDesktop: typeof import('./src/components/search-bar/search-bar-desktop.vue')['default']
    SplashScreen: typeof import('./src/components/splash-screen/splash-screen.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_b883ec8e3b4b4d06b4e1a4d240e3fcc4/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_b883ec8e3b4b4d06b4e1a4d240e3fcc4/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_b883ec8e3b4b4d06b4e1a4d240e3fcc4/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_b883ec8e3b4b4d06b4e1a4d240e3fcc4/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.1.0_@babel+parse_b883ec8e3b4b4d06b4e1a4d240e3fcc4/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
  }
}
